title: "Sony Shop"
url: "https://monsoonmalabar.com/sonyshop"
email: "justinechacko1@gmail.com"
markdown: kramdown
theme-color: "#b00000"
country: "United States of America (the)"
currency_code: "USD"
paypal_email: ""
razorpay_key: ""
location: "11.871601,75.3519669"
page_language: "en"
category: "Kirana Store, FMCG & Grocery"
favicon: "https://i.imgur.com/cE2Kls8.png"
paypal: ""
fb_appid: "494525305893363"
analytics: ""
adsense: ""
sass:
  sass_dir: _sass
  style: compressed
collections:
  products:
    output: true
    permalink: /blog/:name/
defaults:
  - scope:
      type: posts
    values:
      layout: product
  - scope:
      type: products
    values:
      layout: post
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
encoding: UTF-8
permalink: /products/:title/
paginate: 10
paginate_path: 'page/:num/'
